### PR TITLE
ignore this created by mistake

### PR DESCRIPTION
**Pull request by edm00se**

### CODE REVIEW

**Comment by edm00se** [comment]
🤦‍♂️

I should probably un-mark my repo as a fork to prevent this silliness.

**Comment by kentcdodds** [comment]
Maybe I should merge your changes!

**Comment by edm00se** [comment]
Some of my changes are content changes for word dictionary purposes, in addition to some audio api speaking of letter entered / word completed, which is great, but slow; not noticeable to my 5yo but if I type at full speed there's an artifact in the animation of the word. Maybe feature flagging it and configuring for standardized word dictionary default with optional inclusion would be good? 🤔

**Comment by kentcdodds** [comment]
Well, my kids don't really play all that much, but maybe if they start doing it again I'll just pull all of your changes in and make my own modifications 😅

**Comment by edm00se** [comment]
Fair enough. 😆

**Pull request closed without merging**
